### ISSUE TITLE
FIP showing track title only, no artist

### ISSUE THREAD

**Issue by erjonkers** [kamaradclimber/radio-france-home-assistant#5]
I am aware of the overall limitations of FIP for this integration (refresh rate). My challenge is a bit different though: 

The integration works reasonable yet the problem is that **I only see the track title in the entity**. The attributes do show the **album** though but I'd love to include the **artist** as well! Is this fixable or an issue that comes with the API?

![Screenshot 2024-04-30 150629](https://github.com/kamaradclimber/radio-france-home-assistant/assets/121342428/79f347ac-ed6f-4c81-be81-c07c86f7cd0c)

![Screenshot 2024-04-30 150643](https://github.com/kamaradclimber/radio-france-home-assistant/assets/121342428/c473b3b4-4ffb-42ca-bedf-5cb38579f5a8)

Integration version: 0.30
Home-Assistant version: 2024.4.4

**Comment by kamaradclimber** [comment]
Hello,

as far as I can see, the api does not provide the artist. Here is a sample returned for FIP:
```
{
  "data": {
    "grid": [
      {
        "id": "77d8613e-4f96-4a87-9d0b-9ee9b9251220_7",
        "track": {
          "id": "e5074642-2b4e-4b02-979a-5506976f39ba",
          "title": "In the summertime",
          "albumTitle": "Cette annee la 1970"
        }
      },
      {
        "id": "5d8ac25a-d7f2-4a2b-970b-3f1e8275be11_7",
        "track": {
          "id": "3591d343-ee8e-42a1-9616-2442d43f9ac9",
          "title": "Mah-Na, Mah-Na",
          "albumTitle": "Vol. 18 - bottoms up!"
        }
      }
    ]
  }
}
```

**Comment by kamaradclimber** [comment]
Actually the api provides the info, https://github.com/kamaradclimber/radio-france-home-assistant/releases/tag/0.4.0 will contain the feature.
Thanks for the suggestion!

**Comment by erjonkers** [comment]
Impressed by the quick fix! Thank you very much, merci
